In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\Nomitech\Desktop\Machine learning\Boston Dataset.csv")

In [3]:

x = df.drop(columns=['medv','rad'])
y = df['medv']

In [4]:
##normilize some columns that need normalization
cols = ['crim','zn','tax','black']
##Standardization
from sklearn import preprocessing 
scalar = preprocessing.StandardScaler()
#fit our data
scaled_cols= scalar.fit_transform(df[cols])
scaled_cols=pd.DataFrame(scaled_cols,columns=cols)

In [5]:
from sklearn.model_selection import cross_val_score,train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)

### Linear regression with stochastic gradient descent

In [9]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(max_iter=50, penalty=None, eta0=0.1) 

##pigainei max iter diladi kanei itteration 50 fores mesa sto training
#gia auto legete stochastic pigainei tuxeia
sgd_reg.fit(x_train,y_train)

SGDRegressor(eta0=0.1, max_iter=50, penalty=None)

In [11]:
stochastic_pred=sgd_reg.predict(x_test)

In [12]:
from sklearn.metrics import mean_squared_error

lin_mse = mean_squared_error(y_test,stochastic_pred)
lin_rmse=np.sqrt(lin_mse)
print(lin_rmse)

2081270789854340.2


Polynomial Regression
What if your data is actually more complex than a simple straight line? Surprisingly,
you can actually use a linear model to fit nonlinear data. A simple way to do this is to
add powers of each feature as new features, then train a linear model on this extended
set of features. This technique is called Polynomial Regression.


In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree=2,include_bias=False)
x_poly = poly_features.fit_transform(x)
lin_reg=LinearRegression()
lin_reg.fit(x_poly,y)

LinearRegression()

(-95.57285457376011,
 array([-1.40362931e-02, -7.42190602e+00,  7.21847868e-03, -3.50005659e+00,
         2.77788628e+01,  1.93582999e+01,  2.16295299e+01,  8.31339833e-01,
        -4.34922508e+00,  9.74590421e-02, -5.12343563e-01,  8.64000882e-02,
         9.19807085e-01, -5.00145015e-05,  4.05666676e-03,  5.40476003e-05,
        -1.73897047e-03, -1.39334093e-02, -9.67612750e-03,  1.02269833e-02,
        -7.32421146e-05, -6.13664258e-03, -8.64705715e-06, -2.09058416e-04,
         1.03636212e-05,  2.10644175e-03,  1.29941051e-03,  4.23042945e-02,
         2.45711494e-01,  2.83354620e+00, -1.23905063e+00,  2.02463177e-01,
        -1.50330247e-03, -2.60387530e-01, -1.28181257e-02,  4.66737243e-01,
        -2.48027316e-04,  2.04932518e-02,  2.73400534e-04,  9.86261351e-04,
        -4.87573199e-02,  1.46415979e-01, -1.38839317e-02, -8.73402627e-04,
        -5.07621533e-03,  4.61422891e-04, -4.65514138e-03,  1.39022308e-04,
        -8.86805075e-03,  7.18137728e-03, -1.82875001e-01,  3.48755

###  Regularized methods

In [16]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1,solver='cholesky')
ridge_reg.fit(x_train,y_train)

Ridge(alpha=1, solver='cholesky')

In [17]:
##and regularized stochastic
sgd_reg = SGDRegressor(penalty='l2') ##Ridge Regression
sgd_reg.fit(x_train,y_train.ravel())
##Vres ti einai to ravel

SGDRegressor()

In [21]:
## lasso
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(x_train,y_train)


Lasso(alpha=0.1)

In [ ]:
##and regularized stochastic
sgd_reg = SGDRegressor(penalty='l1') ##lasso
sgd_reg.fit(x_train,y_train.ravel())
##Vres ti einai to ravel

So when should you use plain Linear Regression (i.e., without any regularization),
Ridge, Lasso, or Elastic Net? It is almost always preferable to have at least a little bit of
regularization, so generally you should avoid plain Linear Regression. Ridge is a good
default, but if you suspect that only a few features are actually useful, you should pre‐
fer Lasso or Elastic Net since they tend to reduce the useless features’ weights down to
zero as we have discussed. In general, Elastic Net is preferred over Lasso since Lasso
may behave erratically when the number of features is greater than the number of
training instances or when several features are strongly correlated

In [24]:
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.1,l1_ratio=0.5)
elastic_net.fit(x_train,y_train)

ElasticNet(alpha=0.1)

In [25]:
elastic_net.predict(x_test)

array([28.32454455, 34.22568187, 17.43462316, 25.76457057, 18.69168751,
       22.66775978, 17.09247533, 14.79213083, 20.54629995, 20.99903812,
       21.557569  , 18.66677754, -6.5194367 , 21.73359766, 19.10111727,
       24.88739875, 18.24652745,  5.05008843, 39.4386096 , 17.47737889,
       27.3534537 , 29.30388631, 11.74377567, 24.64299301, 18.26726072,
       14.12805409, 23.50995335, 14.45099756, 19.51882124, 20.03099179,
       21.68310648, 25.31952143, 24.87609078, 20.22912848, 14.23818712,
       21.25826496, 31.37622427, 20.59365836, 21.67922634, 25.02113829,
       14.20590741, 30.08678397, 40.74963035, 18.34015018, 27.66720424,
       17.14706269, 14.83349195, 26.24628236, 18.38505761, 32.25385705,
       21.68524338, 32.6338172 , 16.51493418, 27.52329361, 39.0975229 ,
       21.98903791, 19.17299589, 32.34598111, 24.97170433, 12.28354908,
       22.84563265, 30.85089728, 31.57874823, 18.59846835, 23.24259489,
       13.480385  , 19.90071488, 26.60254135, 31.74831045, 12.03

In [ ]:
softmax_reg = LogisticRegression(multi_class="multinomial",solver="lbfgs", C=10)
softmax_reg.fit(X, y)
###softmax

In [6]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [7]:
lin_reg.predict(x_test)

array([28.50005027, 36.21275439, 18.73971189, 25.91322765, 18.05590449,
       24.05293709, 17.09430753, 15.57187555, 21.66925266, 20.61280628,
       24.10643729, 18.5384357 , -6.30823781, 22.83806794, 18.58512158,
       25.40147944, 18.59795339,  4.93094103, 39.95149355, 16.86012414,
       26.84565719, 29.39267446, 11.69134303, 24.0120113 , 17.37349377,
       14.64944103, 24.15107936, 14.32945519, 22.19055375, 19.35432538,
       21.80119956, 24.86249073, 25.30915447, 17.71069454, 15.41491117,
       18.3869364 , 31.49081599, 19.21767627, 24.01746814, 25.46186011,
       13.88762606, 30.12651371, 41.4827136 , 18.5274753 , 27.7236337 ,
       16.37731342, 14.5107157 , 26.73130573, 19.12801824, 31.4212814 ,
       21.29959125, 32.81511304, 16.45152766, 27.56452413, 38.69363177,
       21.9973795 , 18.17666833, 32.12925307, 25.09393548, 12.32654849,
       22.30279155, 30.19726805, 31.15749366, 17.38260331, 22.25687235,
       16.26038001, 19.77009363, 26.44446619, 31.1854772 , 11.41

In [8]:
from sklearn.metrics import mean_squared_error
pred = lin_reg.predict(x_test)
lin_mse = mean_squared_error(y_test,pred)
lin_rmse=np.sqrt(lin_mse)

In [9]:
lin_rmse

4.853220362568736

### the model underfiting lets fix it

In [10]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [11]:
tree_pred = tree_reg.predict(x_test)
tree_mse = mean_squared_error(y_test,tree_pred)
tree_rmse=np.sqrt(tree_mse)

In [12]:
tree_rmse

4.640078549698099

In [13]:
from sklearn.tree import DecisionTreeRegressor
tree_reg2 = DecisionTreeRegressor(max_depth=3)
tree_reg2.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=3)

In [14]:
tree_pred2 = tree_reg2.predict(x_test)
tree_mse = mean_squared_error(y_test,tree_pred2)
tree_rmse=np.sqrt(tree_mse)

In [15]:
tree_rmse

4.4531471209345295

### Cross Validation instead of train_Test_split

In [16]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree_reg,x,y,scoring='neg_mean_squared_error',cv=10)
tree_rmse_scores = np.sqrt(-scores)
print(tree_rmse_scores)

[4.18526828 3.45545888 3.0724583  6.38000861 3.96556254 6.99299369
 4.04823418 9.94002012 9.95931725 6.38606295]


In [17]:
def display_scores(scores):
    print("scores",scores)
    print("mean",scores.mean())
    print("Standard deviations",scores.std())
display_scores(tree_rmse_scores)    

scores [4.18526828 3.45545888 3.0724583  6.38000861 3.96556254 6.99299369
 4.04823418 9.94002012 9.95931725 6.38606295]
mean 5.83853848007894
Standard deviations 2.4187911794073234


In [18]:
from sklearn.model_selection import cross_val_score
scores1 = cross_val_score(tree_reg2,x,y,scoring='neg_mean_squared_error',cv=10)
tree_rmse_scores1 = np.sqrt(-scores1)
print(tree_rmse_scores)

[4.18526828 3.45545888 3.0724583  6.38000861 3.96556254 6.99299369
 4.04823418 9.94002012 9.95931725 6.38606295]


In [19]:
def display_scores(scores):
    print("scores",scores1)
    print("mean",scores1.mean())
    print("Standard deviations",scores1.std())
display_scores(tree_rmse_scores1)   

scores [ -15.34585196  -15.66084277  -11.03302853  -32.78094215  -20.08730124
  -72.01772159  -27.38303932 -101.98850738  -65.51431185  -19.8074093 ]
mean -38.16189560804196
Standard deviations 29.222883472919964


In [20]:
from sklearn.model_selection import cross_val_score
scores2 = cross_val_score(tree_reg,x,y,scoring='neg_mean_squared_error',cv=10)
tree_rmse_scores2 = np.sqrt(-scores2)
print(tree_rmse_scores)

[4.18526828 3.45545888 3.0724583  6.38000861 3.96556254 6.99299369
 4.04823418 9.94002012 9.95931725 6.38606295]


In [21]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(x_train,y_train)

RandomForestRegressor()

In [22]:
from sklearn.model_selection import cross_val_score
score_forest = cross_val_score(forest_reg,x,y,scoring='neg_mean_squared_error',cv=10)
forset_rmse_score = np.sqrt(-score_forest)
forset_rmse_score


array([3.2452347 , 2.30261528, 1.97163977, 4.4289196 , 3.34403002,
       4.82226866, 3.04063382, 9.93590471, 5.08268998, 4.56914055])

In [23]:
forset_rmse_score.mean()

4.274307708252198

###  Fine-tune our model

In [24]:
from sklearn.model_selection import GridSearchCV
param_grid = [
 {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
 {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
 ]


In [25]:
forest_reg  = RandomForestRegressor()
grid_search = GridSearchCV(forest_reg,param_grid,cv=5,scoring='neg_mean_squared_error')
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             scoring='neg_mean_squared_error')

In [26]:
grid_search.best_params_

{'max_features': 6, 'n_estimators': 30}

In [27]:
grid_search.best_estimator_

RandomForestRegressor(max_features=6, n_estimators=30)

In [28]:
##Evaluate our score
cvres = grid_search.cv_results_
for mean_score,params in zip(cvres['mean_test_score'],cvres['params']):
    print(np.sqrt(-mean_score),params)

4.842650996999382 {'max_features': 2, 'n_estimators': 3}
4.310162999060571 {'max_features': 2, 'n_estimators': 10}
3.9400395775951123 {'max_features': 2, 'n_estimators': 30}
4.426905492818086 {'max_features': 4, 'n_estimators': 3}
3.8867941008360294 {'max_features': 4, 'n_estimators': 10}
3.801709606484517 {'max_features': 4, 'n_estimators': 30}
4.800594791376883 {'max_features': 6, 'n_estimators': 3}
4.074551486346605 {'max_features': 6, 'n_estimators': 10}
3.710872692862634 {'max_features': 6, 'n_estimators': 30}
4.800661264906234 {'max_features': 8, 'n_estimators': 3}
3.8419398326975926 {'max_features': 8, 'n_estimators': 10}
3.738319376988002 {'max_features': 8, 'n_estimators': 30}
4.87579263420415 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
4.191712142803794 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
4.349855942993194 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
3.7124671166968373 {'bootstrap': False, 'max_features': 3, 'n_estimators':

In [29]:
grid_search.best_estimator_.feature_importances_

array([0.05024346, 0.04101253, 0.00301712, 0.03264753, 0.00147219,
       0.02850251, 0.32053039, 0.0217314 , 0.06963881, 0.02038421,
       0.02749735, 0.01151734, 0.37180517])

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Nomitech\Desktop\Machine learning\data.csv")

In [3]:
#Encoded the categorical data values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df.iloc[:,1]= encoder.fit_transform(df.iloc[:,1].values)

In [4]:
##Split the data into independed and depenend data sets
x = df.iloc[:,2:31].values
y = df.iloc[:,1].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

# CLASSIFICATION  

In [6]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(random_state=42)
sgd.fit(x_train,y_train)

SGDClassifier(random_state=42)

In [7]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd,x,y,cv=5,scoring='accuracy')


array([0.9122807 , 0.9122807 , 0.89473684, 0.95614035, 0.87610619])

In [8]:
sgd.predict(x_test)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [9]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [10]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd,x_train,y_train,cv=5)

Just like the cross_val_score() function, cross_val_predict() performs K-fold
cross-validation, but instead of returning the evaluation scores, it returns the predic‐
tions made on each test fold. This means that you get a clean prediction for each
instance in the training set (“clean” meaning that the prediction is made by a model
that never saw the data during training).


In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_pred)

##243 true px nengatives correctly classifier 24 false wrongly classified,false positives
##koitakse to sto internet


array([[243,  24],
       [ 38, 121]], dtype=int64)

In [13]:
##Precision and recall scores tsekare ta sto internet
from sklearn.metrics import precision_score,recall_score
precision_score(y_train,y_train_pred)

0.8344827586206897

In [14]:
recall_score(y_train, y_train_pred) 

0.7610062893081762

In [15]:
##auta ta 2 mporeis na ta tairiakseis ston f1 score
from sklearn.metrics import f1_score

In [16]:
f1_score(y_train,y_train_pred)

0.7960526315789475