In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv(r"C:\Users\Nomitech\Desktop\Udemy Machine learning\Machine Learning A-Z (Codes and Datasets)\Part 2 - Regression\Section 7 - Support Vector Regression (SVR)\Python\Position_Salaries.csv")

In [3]:
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [4]:
x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

### Feature scaling

In [6]:
#kanoume feature scaling se y giati exei megalo range
##we reshape the the standardization class wants 2 d array

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000], dtype=int64)

In [9]:
y = y.reshape(len(y),1)


In [10]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]], dtype=int64)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
sc_y = StandardScaler()
y = sc_y.fit_transform(y)

In [13]:
x

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [14]:
y

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815],
       [-0.35033854],
       [-0.17428902],
       [ 0.17781001],
       [ 0.88200808],
       [ 2.64250325]])

In [19]:
from sklearn.svm import SVR
regressor = SVR( kernel = 'rbf')
regressor.fit(x,y)


C:\Users\Nomitech\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [24]:
## prepei na kanoume reverse the scaling gia na paroume pragmatika values
sc_y.inverse_transform(regressor.predict(sc.transform([[6.5]])))
#vima ena fonazoume to scaler pou tou sc gia na parei to 6.5 kai na to kanei noumero se scaling
#vima 2 to vazoume to scaler tou y gia na paroume to apotelesma tou

array([252789.13921624])